var supertest = require('supertest')
const request = supertest("http://localhost:3000/")
require('dotenv').config()
console.log(process.env) 
it("Should return the email of current user",async function(){
    
    const response = await  request.get('api/user/current').set("X-Metabase-Session",process.env.token)
    expect(response.body.email).toEqual("hmmahir2001@gmail.com")
   
}) 

it("It should return the recent activity",async function(){
    
    const response = await  request.get('api/activity').set("X-Metabase-Session",process.env.token)
    expect(response.status).toEqual(200)
   
}) 


it("SHould return the collections",async function(){
    
    const response = await  request.get('api/collection').set("X-Metabase-Session",process.env.token)
    var jsonData = JSON.parse(response.text);
    expect(jsonData[0].name).toEqual("Our analytics")
   
}) 
it("Should return the collection with ID 1",async function(){
    
    const response = await  request.get('api/collection/1').set("X-Metabase-Session",process.env.token)
    expect(response.body.name).toEqual("Muhammad Mahir's Personal Collection")
   
}) 
it("Should fetch all bookmark",async function(){
    
    const response = await  request.get('api/bookmark').set("X-Metabase-Session",process.env.token)
    var jsonData = JSON.parse(response.text);
    expect(jsonData[0].name).toEqual("Test Question Generated By API POST Call")
})  
it("Should return the admin email",async function(){
    
    const response = await   request.get('api/setting/admin-email').set("X-Metabase-Session",process.env.token)
    expect(response.text).toEqual("hmmahir2001@gmail.com")
   
})
it('Should post a question', async function(){
    const card = require("./card.json");
    const response = await request.post('api/card')
      .send(JSON.stringify(card))
      .set('Content-Type', 'application/json')
      .set('Accept', 'application/json')
      .set("X-Metabase-Session",process.env.token);
      expect(response.body.name).toEqual("Test Question Generated By API POST Call");
  });
 
it("Should return the recent login activity", async function(){
    const response = await  request.get('api/login-history/current').set("X-Metabase-Session",process.env.token)
    var jsonData = JSON.parse(response.text);
    expect(jsonData[0].ip_address).toEqual(process.env.ip)
});


it("Should return databses with id1", async function(){
    const response = await  request.get('api/database/1').set("X-Metabase-Session",process.env.token)
    expect(response.body.name).toEqual("Sample Database")

})
  //Sample Test case
  /*
    it('should POST JSON', function(done) {
    supertest(app)
      .post('/postjson')
      .send({
        'id': 1,
        'name': 'Mike'
      })
      .set('Content-Type', 'application/json')
      .set('Accept', 'application/json')
      .expect(200)
      .end(function (err, res) {
        if (err) throw err;
        console.log(res.body);
        done();
      });
  });
  */
