var supertest = require('supertest')
const request = supertest("http://localhost:3000/")
it("Should return the email of current user",async function(){
    
    const response = await  request.get('api/user/current').set("X-Metabase-Session","523067db-fc3c-4e34-8de7-2b0709d4eb5b")
    //console.log("got this : "+ response.body.email)
    expect(response.body.email).toEqual("hammadnhassan7799@gmail.com")
   
}) 

it("It should return the recent activity",async function(){
    
    const response = await  request.get('api/activity').set("X-Metabase-Session","523067db-fc3c-4e34-8de7-2b0709d4eb5b")
    console.log("table id is "+response.body.table_id)
    expect(response.status).toEqual(200)
   
}) 


it("SHould return the collections",async function(){
    
    const response = await  request.get('api/collection').set("X-Metabase-Session","523067db-fc3c-4e34-8de7-2b0709d4eb5b")
    //console.log("collection response is : "+(response).text)
    var jsonData = JSON.parse(response.text);
     /*
    for (var i = 0; i < jsonData.length; i++) {
        var counter = jsonData[i];
        console.log(counter.name);
    }*/
    expect(jsonData[0].name).toEqual("Our analytics")
   
}) 
it("Should return the collection with ID 1",async function(){
    
    const response = await  request.get('api/collection/1').set("X-Metabase-Session","523067db-fc3c-4e34-8de7-2b0709d4eb5b")
    console.log("this is ress: "+response.body.name)
    expect(response.body.name).toEqual("muhammad Hammad's Personal Collection")
   
}) 
it("Should fetch all bookmark",async function(){
    
    const response = await  request.get('api/bookmark').set("X-Metabase-Session","523067db-fc3c-4e34-8de7-2b0709d4eb5b")
    var jsonData = JSON.parse(response.text);
    expect(jsonData[0].name).toEqual("Test Question Generated By API POST Call")
})  
/*
it("Testing Question",async function(){
    
    const response = await   request.post('api/card').set("X-Metabase-Session","ac629326-ea77-4739-ae73-1c1b263e448c")
  
    expect(response.status).toEqual(200)
   
}) */

it("Should return the admin email",async function(){
    
    const response = await   request.get('api/setting/admin-email').set("X-Metabase-Session","523067db-fc3c-4e34-8de7-2b0709d4eb5b")
    expect(response.text).toEqual("hammadnhassan7799@gmail.com")
   
}) 
/*
it("Testing creating Cards",async function(){
    const card = require("./card.json");
    console.log("this is in card file : "+JSON.stringify(card));
    const response = await   request.get('api/card').set("X-Metabase-Session","ac629326-ea77-4739-ae73-1c1b263e448c")
    expect(response.text).toEqual("hammadnhassan7799@gmail.com")
   
}) 
*/
it('Should post a question', async function(){
    const card = require("./card.json");
    const response = await request.post('api/card')
      .send(JSON.stringify(card))
      .set('Content-Type', 'application/json')
      .set('Accept', 'application/json')
      .set("X-Metabase-Session","523067db-fc3c-4e34-8de7-2b0709d4eb5b");
      console.log("name of the card: "+response.body.name);
      expect(response.body.name).toEqual("Test Question Generated By API POST Call");
  });
 
it("Should return the recent login activity", async function(){
    const response = await  request.get('api/login-history/current').set("X-Metabase-Session","523067db-fc3c-4e34-8de7-2b0709d4eb5b")
    var jsonData = JSON.parse(response.text);
    expect(jsonData[0].ip_address).toEqual("172.17.0.1")
});

/*
it("Should return all databses", async function(){
    const response = await  request.get('api/database').set("X-Metabase-Session","523067db-fc3c-4e34-8de7-2b0709d4eb5b")
    console.log("getting this databses: "+JSON.stringify(response.text));
    const db = JSON.stringify(response.text);
    console.log("name "+db.total)
    expect(response.text.data.name).toEqual("Sample Database")
    expect(response.body.total).toEqual("1")
})*/
it("Should return databses with id1", async function(){
    const response = await  request.get('api/database/1').set("X-Metabase-Session","523067db-fc3c-4e34-8de7-2b0709d4eb5b")
    expect(response.body.name).toEqual("Sample Database")

})
  //Sample Test case
  /*
    it('should POST JSON', function(done) {
    supertest(app)
      .post('/postjson')
      .send({
        'id': 1,
        'name': 'Mike'
      })
      .set('Content-Type', 'application/json')
      .set('Accept', 'application/json')
      .expect(200)
      .end(function (err, res) {
        if (err) throw err;
        console.log(res.body);
        done();
      });
  });
  */
